<a href="https://colab.research.google.com/github/alagiehafigue/ai-ml-engineering/blob/main/data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import numpy as np

df = pd.read_csv('clinic_intake.csv')
df

    patient_id   age sex region smoker   bmi
0         1001  34.0   M  North     no  24.5
1         1002  41.0   F  South    yes  31.2
2         1003  29.0   F   East     no  22.0
3         1004   NaN   M  North    yes  27.8
4         1005  52.0   M  South     no  29.1
5         1006  45.0   F    NaN     no  26.4
6         1007  38.0   M   East    yes  30.0
7         1008  27.0   F  North     no  21.5
8         1009  60.0   M  South    yes  28.3
9         1010  33.0   F   East     no   NaN
10        1011  48.0   M  North     no  25.9
11        1012   NaN   F  South     no  23.7
12        1013  55.0   M    NaN    yes  32.1
13        1014  39.0   F   East    yes  27.0
14        1015  44.0   M  North     no  26.6
15        1016  31.0   F    NaN     no  24.9
16        1017  50.0   M  South    yes  30.8
17        1018  36.0   F   East     no  22.4

In [36]:
df.isnull().sum()

patient_id    0
age           2
sex           0
region        3
smoker        0
bmi           1
dtype: int64

In [37]:
df["age"] = df['age'].fillna(df['age'].mean())
df["bmi"] = df['bmi'].fillna(df['bmi'].mean())
df = df.dropna()
df.isnull().sum()

patient_id    0
age           0
sex           0
region        0
smoker        0
bmi           0
dtype: int64

In [38]:
df

    patient_id     age sex region smoker        bmi
0         1001  34.000   M  North     no  24.500000
1         1002  41.000   F  South    yes  31.200000
2         1003  29.000   F   East     no  22.000000
3         1004  41.375   M  North    yes  27.800000
4         1005  52.000   M  South     no  29.100000
6         1007  38.000   M   East    yes  30.000000
7         1008  27.000   F  North     no  21.500000
8         1009  60.000   M  South    yes  28.300000
9         1010  33.000   F   East     no  26.717647
10        1011  48.000   M  North     no  25.900000
11        1012  41.375   F  South     no  23.700000
13        1014  39.000   F   East    yes  27.000000
14        1015  44.000   M  North     no  26.600000
16        1017  50.000   M  South    yes  30.800000
17        1018  36.000   F   East     no  22.400000

In [39]:
df = df.drop(columns=['patient_id'])
df

       age sex region smoker        bmi
0   34.000   M  North     no  24.500000
1   41.000   F  South    yes  31.200000
2   29.000   F   East     no  22.000000
3   41.375   M  North    yes  27.800000
4   52.000   M  South     no  29.100000
6   38.000   M   East    yes  30.000000
7   27.000   F  North     no  21.500000
8   60.000   M  South    yes  28.300000
9   33.000   F   East     no  26.717647
10  48.000   M  North     no  25.900000
11  41.375   F  South     no  23.700000
13  39.000   F   East    yes  27.000000
14  44.000   M  North     no  26.600000
16  50.000   M  South    yes  30.800000
17  36.000   F   East     no  22.400000

In [40]:
df.shape

(15, 5)

In [41]:
df = pd.get_dummies(df, columns=['sex', 'region', 'smoker'])
df

,age,bmi,sex_F,sex_M,region_East,region_North,region_South,smoker_no,smoker_yes
0,34.000,24.500000,False,True,False,True,False,True,False
1,41.000,31.200000,True,False,False,False,True,False,True
2,29.000,22.000000,True,False,True,False,False,True,False
3,41.375,27.800000,False,True,False,True,False,False,True
4,52.000,29.100000,False,True,False,False,True,True,False
6,38.000,30.000000,False,True,True,False,False,False,True
7,27.000,21.500000,True,False,False,True,False,True,False
8,60.000,28.300000,False,True,False,False,True,False,True
9,33.000,26.717647,True,False,True,False,False,True,False
10,48.000,25.900000,False,True,False,True,False,True,False
11,41.375,23.700000,True,False,False,False,True,True,False
13,39.000,27.000000,True,False,True,False,False,False,True
14,44.000,26.600000,False,True,False,True,False,True,False
16,50.000,30.800000,False,True,False,False,True,False,True
17,36.000,22.400000,True,False,True,False,False,True,False

In [42]:
df.shape

(15, 9)

In [43]:
amin, amax = df['age'].min(), df['age'].max()
df['age'] = (df['age'] - amin) / (amax - amin)

bmin, bmax = df['bmi'].min(), df['bmi'].max()
df['bmi'] = (df['bmi'] - bmin) / (bmax - bmin)

df

,age,bmi,sex_F,sex_M,region_East,region_North,region_South,smoker_no,smoker_yes
0,0.212121,0.309278,False,True,False,True,False,True,False
1,0.424242,1.000000,True,False,False,False,True,False,True
2,0.060606,0.051546,True,False,True,False,False,True,False
3,0.435606,0.649485,False,True,False,True,False,False,True
4,0.757576,0.783505,False,True,False,False,True,True,False
6,0.333333,0.876289,False,True,True,False,False,False,True
7,0.000000,0.000000,True,False,False,True,False,True,False
8,1.000000,0.701031,False,True,False,False,True,False,True
9,0.181818,0.537902,True,False,True,False,False,True,False
10,0.636364,0.453608,False,True,False,True,False,True,False
11,0.435606,0.226804,True,False,False,False,True,True,False
13,0.363636,0.567010,True,False,True,False,False,False,True
14,0.515152,0.525773,False,True,False,True,False,True,False
16,0.696970,0.958763,False,True,False,False,True,False,True
17,0.272727,0.092784,True,False,True,False,False,True,False

In [44]:
from sklearn.model_selection import train_test_split
x_train, x_test = train_test_split(df, test_size= 0.2, random_state=1)
print(x_train.shape, x_test.shape)

(12, 9) (3, 9)